name: Verify Arsi Bypass PoC

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Versão estável que não dá erro de Logger
        bundler-cache: true

    - name: Install SQLite Dev
      run: sudo apt-get install -y libsqlite3-dev

    - name: Run PoC
      run: |
        # Adiciona sqlite3 ao Gemfile temporariamente para o teste
        echo "gem 'sqlite3'" >> Gemfile
        bundle install
        # Roda o teste ignorando erros de carga local
        bundle exec ruby -I"lib" test/poc_bypass_global.rb
