name: Verify Arsi Bypass PoC

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Atualizado para suportar Arsi 1.3.0

    - name: Install System Dependencies
      run: sudo apt-get install -y libsqlite3-dev

    - name: Install Gems Manually
      run: |
        gem install activerecord -v 7.0.8.7
        gem install sqlite3
        gem install minitest
        gem install arsi -v 1.3.0

    - name: Run PoC (The Exploit)
      run: |
        ruby -I"lib" test/poc_bypass_global.rb
