name: Verify Arsi Bypass PoC

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Vers√£o mais atualizada
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true # O SEGREDO: Ele instala tudo do seu Gemfile automaticamente e faz o cache

    - name: Run PoC (The Exploit)
      run: bundle exec ruby -I"lib" test/poc_bypass_global.rb
